import { jsPDF } from 'jspdf';
import { GeneratedSpeech } from '../types';

export const generatePDF = (speech: GeneratedSpeech) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFont("times", "bold");
  doc.setFontSize(22);
  const splitTitle = doc.splitTextToSize(speech.title, 180);
  doc.text(splitTitle, 15, 20);

  // Content
  doc.setFont("times", "normal");
  doc.setFontSize(12);
  
  const contentLines = doc.splitTextToSize(speech.content, 180);
  let y = 20 + (splitTitle.length * 10) + 10;
  
  // Basic pagination loop
  const pageHeight = doc.internal.pageSize.height;
  
  contentLines.forEach((line: string) => {
    if (y > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, 15, y);
    y += 7;
  });
  
  // Footer
  const dateStr = new Date(speech.timestamp).toLocaleDateString();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Generated by "I Need a Speech" on ${dateStr}`, 15, pageHeight - 10);

  doc.save(`${speech.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
};
